// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMrTVokPYe-l2ejgiTxYAyKQ53uFh4PyI',
    appId: '1:388112038631:web:d1b81c80d6b5a3b924c042',
    messagingSenderId: '388112038631',
    projectId: 'flash-chat-58025',
    authDomain: 'flash-chat-58025.firebaseapp.com',
    storageBucket: 'flash-chat-58025.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV6WesQ7v1zJr1wxMD_Kz3axa0la8b4GM',
    appId: '1:388112038631:android:f3741567f457c36b24c042',
    messagingSenderId: '388112038631',
    projectId: 'flash-chat-58025',
    storageBucket: 'flash-chat-58025.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoUjB7oj-7ZiH9M3UhOzkum5qSbuTOkeQ',
    appId: '1:388112038631:ios:6970f8d1eb3e0d6a24c042',
    messagingSenderId: '388112038631',
    projectId: 'flash-chat-58025',
    storageBucket: 'flash-chat-58025.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoUjB7oj-7ZiH9M3UhOzkum5qSbuTOkeQ',
    appId: '1:388112038631:ios:6970f8d1eb3e0d6a24c042',
    messagingSenderId: '388112038631',
    projectId: 'flash-chat-58025',
    storageBucket: 'flash-chat-58025.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );
}
